# Generated by Django 5.0.3 on 2024-04-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns_app', '0002_rename_campaing_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
