# Generated by Django 5.0.3 on 2024-04-01 18:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('strength_buff', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('intelligence_buff', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('wisdom_buff', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('charisma_buff', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('constitution_buff', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('speed_buff', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('image', models.URLField()),
                ('role', models.CharField(max_length=75)),
                ('strength', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('intelligence', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('wisdom', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('charisma', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('constitution', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('speed', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('healthPoint', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('healthPointMax', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('mana', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('manaMax', models.IntegerField(validators=[django.core.validators.MinValueValidator(5)])),
                ('exp', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('expMax', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sheets_app.race')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('attack', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('defense', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets_app.sheet')),
            ],
        ),
    ]
