# Generated by Django 5.0.3 on 2024-04-01 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='manaMax',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
