# Generated by Django 5.0.3 on 2024-04-01 19:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campaing',
            new_name='Campaign',
        ),
    ]
