# Generated by Django 5.0.3 on 2024-05-05 16:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns_app', '0005_campaign_uuid_alter_campaign_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='id',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
