# Generated by Django 5.0.3 on 2024-05-16 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns_app', '0006_rename_uuid_campaign_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('strength_buff', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('intelligence_buff', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('wisdom_buff', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('charisma_buff', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('constitution_buff', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('speed_buff', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
