# Generated by Django 5.0.3 on 2024-05-05 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns_app', '0006_remove_campaign_id_alter_campaign_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='uuid',
            new_name='id',
        ),
    ]
