# Generated by Django 5.0.3 on 2024-05-16 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns_app', '0007_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races', to='campaigns_app.campaign'),
        ),
    ]
