# Generated by Django 5.0.3 on 2024-05-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns_app', '0008_race_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='code',
            field=models.CharField(default='jaa8oR74', editable=False, max_length=8, unique=True),
        ),
    ]
