# Generated by Django 5.0.3 on 2024-05-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns_app', '0011_alter_campaign_code_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='role',
        ),
        migrations.AddField(
            model_name='class',
            name='roles',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='code',
            field=models.CharField(default='tn897cE7', editable=False, max_length=8, unique=True),
        ),
    ]
