# Generated by Django 5.0.3 on 2024-05-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns_app', '0012_remove_class_role_class_roles_alter_campaign_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='code',
            field=models.CharField(default='BqXVr2dw', editable=False, max_length=8, unique=True),
        ),
    ]
