# Generated by Django 5.0.3 on 2024-05-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns_app', '0015_alter_campaign_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='code',
            field=models.CharField(default='qRNNJqHb', editable=False, max_length=8, unique=True),
        ),
    ]
