# Generated by Django 5.0.3 on 2024-05-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns_app', '0016_alter_campaign_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='is_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='code',
            field=models.CharField(default='dVkYvuUn', editable=False, max_length=8, unique=True),
        ),
    ]
