<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-05-29 21:04

=======
# Generated by Django 5.0.3 on 2024-05-29 22:21

import campaigns_app.models
>>>>>>> 0b339845ddd3bbd4f0af4aadc1870c0442b65119
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns_app', '0017_class_is_used_race_is_used_alter_campaign_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='code',
<<<<<<< HEAD
            field=models.CharField(default='kFkx73hS', editable=False, max_length=8, unique=True),
=======
            field=models.CharField(default=campaigns_app.models.generate_unique_code, editable=False, max_length=8, unique=True),
>>>>>>> 0b339845ddd3bbd4f0af4aadc1870c0442b65119
        ),
    ]
