# Generated by Django 5.0.3 on 2024-05-29 22:21

import campaigns_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns_app', '0017_class_is_used_race_is_used_alter_campaign_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='code',
            field=models.CharField(default=campaigns_app.models.generate_unique_code, editable=False, max_length=8, unique=True),
        ),
    ]
