# Generated by Django 5.0.3 on 2024-05-16 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Race',
        ),
    ]
