# Generated by Django 5.0.3 on 2024-05-20 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns_app', '0010_alter_campaign_code'),
        ('sheets_app', '0002_delete_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns_app.campaign'),
        ),
    ]
