# Generated by Django 5.0.3 on 2024-04-02 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_app', '0004_alter_sheet_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='expMax',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
