# Generated by Django 5.0.3 on 2024-04-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_app', '0006_alter_sheet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='description',
            field=models.TextField(default='NULL'),
        ),
    ]
