# Generated by Django 5.0.3 on 2024-04-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_app', '0007_alter_sheet_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='image',
            field=models.URLField(max_length=65534, null=True),
        ),
    ]
