# Generated by Django 5.0.3 on 2024-04-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_app', '0008_alter_sheet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='image',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
