# Generated by Django 5.0.3 on 2024-04-08 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_app', '0010_alter_sheet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='expTotal',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
