# Generated by Django 5.0.3 on 2024-05-05 18:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_app', '0014_remove_magic_dice_quantity_remove_magic_dice_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
