# Generated by Django 5.0.3 on 2024-05-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_app', '0016_alter_equipment_magic_foreign_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='sheet_id',
        ),
        migrations.RemoveField(
            model_name='magic',
            name='sheet_id',
        ),
    ]
