# Generated by Django 5.0.3 on 2024-05-05 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_app', '0017_remove_equipment_sheet_id_remove_magic_sheet_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='uuid',
            new_name='id',
        ),
    ]
