# Generated by Django 5.0.3 on 2024-05-05 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_app', '0020_remove_equipment_id_alter_equipment_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='uuid',
            new_name='id',
        ),
    ]
